module "sg_dispatch" {
  source                = "../modules/tf-sg/dispatch"
  tags                  = "${var.tags}"
  region                = "${var.region}"
  environment           = "${var.environment}"
  SG_Name               = "${lower(var.tags["client"])}-${var.dispatch["role"]}-nsg"
  resource_group_name   = "${upper(var.tags["client"])}-RG"
  # serverinfo            = "${var.dispatch}"
  mgmt_subnets          = "${var.mgmt_subnets}"
}

module "dispatch" {
  source                      = "../../modules/tf-createinstance"
  ssh_public_key              = "${var.ssh_public_key_location}"
  subnet_id                   = "/subscriptions/${var.subscription_id}/resourceGroups/${var.tags["client"]}-RG/providers/Microsoft.Network/virtualNetworks/${var.tags["client_lc"]}-network/subnets/vnet${var.environment}"
  network_security_group_id   = "/subscriptions/${var.subscription_id}/resourceGroups/${var.tags["client"]}-RG/providers/Microsoft.Network/networkSecurityGroups/${var.tags["client_lc"]}-${var.dispatch["role"]}-nsg"
  azurename_prefix            = "${var.tags["client_lc"]}${var.environment}"
  hostname                    = "${var.tags["client_lc"]}-${var.environment}${var.dispatch["role"]}-srv"
  region                      = "${var.region}"
  serverscount                = "${var.dispatch["count"]}"
  environment                 = "${var.environment}"
  os_user                     = "${var.os_user}"
  resource_group_name         = "${upper(var.tags["client"])}-RG"
  network_security_group_name = "${lower(var.tags["client"])}-${var.dispatch["role"]}-nsg"
  network_resource_group_name = "${lower(var.tags["client"])}-network"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
}

module "dispatch_boostrap" {
  source                      = "../../modules/tf-linux"
  user_data                   = "../../scripts/linux-common.sh"
  aem_data                    = "../../scripts/buildaem.sh"
  ssh_private_key             = "${var.ssh_private_key_location}"
  ssh_public_key              = "${var.ssh_public_key_location}"
  pub_ips                     = "${module.dispatch.servers_pubip_address}"
  storageacct                 = "${var.storage_account_name}"
  os_user                     = "${var.os_user}"
  chef_project                = "${var.chef_project}"
  serverscount                = "${var.dispatch["count"]}"
  role                        = "${var.dispatch["role"]}"
  region                      = "${var.region}"
  environment                 = "${var.environment}"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
  # chef_runlist                 = "chef-client -E ${var.environment} -o role[publish]"
  # depends_list                 = ""
}

module "lb" {
  source                      = "../../modules/tf-lb"
  azurename_prefix            = "${lower(var.tags["client"])}${var.environment}"
  hostname                    = "${lower(var.tags["client"])}-${var.environment}${var.dispatch["role"]}-srv"
  region                      = "${var.region}"
  serverscount                = "${var.dispatch["count"]}"
  environment                 = "${var.environment}"
  resource_group_name         = "${var.tags["client"]}-RG"
  tags                        = "${var.tags}"
  serverinfo                  = "${var.dispatch}"
  server_names                = "${module.dispatch.server_names}"
  network_security_group_id   = "${module.dispatch.servers_network_security_group_id}"
  subnet_id                   = "${module.dispatch.servers_subnet_id}"
  public_ip_address_id        = "${module.dispatch.server_pubip_id}"
  tracked_url                 = "${var.tracked_url}"
}
